# =============================================================================
# TOOL CATALOG (generated from catalog.json by scripts/build.ts — do not edit)
# =============================================================================
# Fields: id|kind|target|app|bin|name|requires|post

CATALOG=(
    "ghostty|cask|ghostty|Ghostty||Ghostty||"
    "nerd-font|cask|font-jetbrains-mono-nerd-font|||JetBrains Mono Nerd Font||"
    "starship|brew|starship|||Starship||"
    "claude-code|curl|https://claude.ai/install.sh||claude|Claude Code||"
    "codex|brew|codex|||Codex CLI||"
    "pi|bun|@earendil-works/pi-coding-agent||pi|Pi|bun|"
    "opencode|bun|opencode-ai||opencode|OpenCode|bun|"
    "crush|bun|@charmland/crush||crush|Crush|bun|"
    "herdr|brew|herdr|||Herdr||"
    "orca|cask|stablyai/orca/orca|Orca||Orca||"
    "ccpeek|brew|ahmedelgabri/tap/ccpeek||ccpeek|ccpeek||"
    "caveman|plugin|JuliusBrussee/caveman|||Caveman|claude-code|"
    "agent-browser|bun|agent-browser||agent-browser|Agent Browser|bun|agent-browser install"
    "zed|cask|zed|Zed||Zed||"
    "cursor|cask|cursor|Cursor||Cursor||"
    "vscode|cask|visual-studio-code|Visual Studio Code||Visual Studio Code||"
    "git|brew|git|||Git||"
    "gh|brew|gh|||GitHub CLI||"
    "lazygit|brew|lazygit|||lazygit||"
    "git-delta|brew|git-delta||delta|delta||"
    "eza|brew|eza|||eza||"
    "bat|brew|bat|||bat||"
    "zoxide|brew|zoxide|||zoxide||"
    "fzf|brew|fzf|||fzf||"
    "ripgrep|brew|ripgrep||rg|ripgrep||"
    "fd|brew|fd|||fd||"
    "btop|brew|btop|||btop||"
    "mkcert|brew|mkcert|||mkcert||"
    "jq|brew|jq|||jq||"
    "trash-cli|bun|trash-cli||trash|trash-cli|bun|"
    "node|brew|node|||Node.js||"
    "bun|brew|bun|||Bun||"
    "shottr|cask|shottr|Shottr.app||Shottr||"
    "handy|cask|handy|Handy.app||Handy||"
)
